/*
* Abstract class from which all Jxfs event classes are extended.
* This event class contains the generic variables for all the events. It extends java.util.EventObject. It is not used on its own but serves as a base class for the other J/XFS event types.
*/
package com.jxfs.events;

import java.util.Date;
import java.util.EventObject;

/**
 * The JxfsEvent class is the foundation for all event classes within the J/XFS framework. 
 * This abstract class provides the basic functionality and structure for representing events generated by J/XFS-compliant devices. 
 * 
 */
public class JxfsEvent extends EventObject  {
	private Date date; 
    public JxfsEvent(Object source) {
		super(source);
		this.date = new Date(); // initializes property with the current date/time
	}

	/*
    * Contains the date the event was first created. If the event comes from a remote machine then the date will be the time the event was created on the remote machine.
    */
    public Date getWhen() {
		return date;
	}

    /*
    * Sets the source of this event. This is filled with the Device Service object (as the events are generated here), but is replaced by the Device Control object before it is passed to the application.
    */
    void setSource(Object source) {}

    /*
    * Returns the source of the event. Object getSource() (Inherited from the EventObject class). 
    * Return:
    *   IJxfsBaseService 
    *   IJxfsBaseControl 
    */    
}